name: Import Issues

on:
  push:
    branches:
      - main  # or the branch where you want to trigger the workflow

jobs:
  import_issues:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install dependencies
        run: |
          npm install axios fs path
      
      - name: Run import-issues script
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: node import-issues.js
